### ISSUE TITLE
algorithms: add fencing where needed 

### ISSUE THREAD

**Issue by fnrizzi** [NexGenAnalytics/kokkos#12]

**Comment by cz4rs** [comment]
- global fences replaced 
- labels added

What's left is to examine when we can skip fencing completely (there might be some that are redundant).

**Comment by fnrizzi** [comment]
I think the current fences are not fully correct because the execution space is a universal reference:
```cpp
void something(ExecutionSpace&& ex) 
{
  ::Kokkos::parallel_reduce(..., 
     RangePolicy<ExecutionSpace>(std::forward<ExecutionSpace>(ex), 0,  num_elements), ...);
  ex.fence("minmax_element: fence after operation");
}
```
ex could have been moved from inside rangePolicy  so I think we need to change this

**Comment by cz4rs** [comment]
Fencing seems to be in decent shape, all the remaining issues should be addressed directly in review. Closing.
