### ISSUE TITLE
algorithms: improve design of unit tests 

### ISSUE THREAD

**Issue by fnrizzi** [NexGenAnalytics/kokkos#14]
Need to improve how we design the unit tests to make it more flexible. Not super urgent, but it would be good to that at some point.

**Comment by cz4rs** [comment]
Having [typed tests](https://github.com/google/googletest/blob/master/docs/advanced.md#typed-tests) would be really helpful, but it seems that Kokkos is using a stripped down (or older) version of googletest. Seeing that gtest lives in `tpls` directory (and the notes in `README` there) it might be hard to get it upgraded.

**Comment by fnrizzi** [comment]
yes I agree! I think we need to work without that. 
Btw, to use templated classes, we could for the time being using an alias: 
```c++
template <typename T>
class FooTest : public testing::Test {
 public:
  ...
  using List = std::list<T>;
  static T shared_;
  T value_;
};
using foo_int = FooTest<int>;

TEST_F(foo_int, ...){}
```
I think this works , I know it is not the same, but still something

**Comment by fnrizzi** [comment]
@cz4rs do you think we can close this? I think it is fine how we do testing

**Comment by cz4rs** [comment]
Agreed, closing as testing coverage and quality has reached sufficient level. Other improvements can be added in parallel with regular work.
