### ISSUE TITLE
algorithms: add necessary documentation

### ISSUE THREAD

**Issue by cz4rs** [NexGenAnalytics/kokkos#16]
Add reasonable amount of documentation for the implemented algorithms.

Things to consider:
- where to put it: doxygen or wiki only?
- if doxygen, should it be repeated for each overload? (there's plenty of them)
- performance remarks - these could be important, although they depend on the implementation -> only some of the algorithms use `Kokkos::parallel*` underneath

**Comment by fnrizzi** [comment]
> performance remarks - these could be important, although they depend on the implementation -> only some of the algorithms use Kokkos::parallel* underneath

that is just temporary, right? eventually most of them will use parallel inside. you agree?

**Comment by cz4rs** [comment]
Well, I'm not so sure about that - see the discussion we've had with `find_if`. We should definitely strive for as much parallelism as possible, but we'll see what awaits in categories B and C.

**Comment by cz4rs** [comment]
`for_each.cpp` example demonstrating the use of `Kokkos::Experimental::for_each` was removed and the only guidance provided to the potential users are unit tests and scarce comments in the imlpementation.

Note: in case that documentation is prioritized, remember to add some concise examples.
