### ISSUE TITLE
algorithms: consider parallel approach for `find_if`

### ISSUE THREAD

**Issue by cz4rs** [NexGenAnalytics/kokkos#17]
_Based on the discussion with @crtrott and @fnrizzi._

`Kokkos::Experimental::find*` family of algorithms is simply looping over the passed View.

For thread based backends, it could chunk it up and loop over chunks, combined with a flag check:
```
View<int> done("DONE");
int chunks = N/chunk_size;
parallel_for(chunks, KOKKOS_LAMBDA(int ii) {
  while(!done()) {
    bool found;
    for(int i=ii*chunk_size; i++; i<(ii+1)*chunk_size) found = f(i);
    if(found) done()=1;
  }
});
```

Notes about chunks granularity:
> you should do this only for backends which are not GPU like
> and then basically ask the execution space for its concurrency

> that kinda tells you how many threads you have
> and then for this to make sense each thread needs a bunch of chunks

> so maybe something like chunk_size = N/Exec().concurrency()/10
> so every 10% of work you kinda check

**Comment by fnrizzi** [comment]
One more thought: I think we can implement find_if as a reduction. One problem with using the solution above is that it cannot be used within a team parfor and that is should be avoided on GPU like systems. If we implemented find_if as a reduction we can also support the team parfor and also nothing would change for gpu.

**Comment by fnrizzi** [comment]
should we close this?

**Comment by cz4rs** [comment]
Closing after @fnrizzi has provided a parallel implementation (see [non-modifying ops](https://github.com/NexGenAnalytics/kokkos/blob/for_each_4075/algorithms/src/std_algorithms/Kokkos_NonModifyingSequenceOperations.hpp)).
