### ISSUE TITLE
algorithms: missing KOKKOS_INLINE_FUNCTION

### ISSUE THREAD

**Issue by fnrizzi** [NexGenAnalytics/kokkos#18]
I think all/most of algorithms should have KOKKOS_INLINE_FUNCTION such that they can be called on device

**Comment by fnrizzi** [comment]
@cz4rs I do think this is relevant: see this https://github.com/kokkos/kokkos/wiki/HierarchicalParallelism

**Comment by cz4rs** [comment]
Note that since `parallel_for` and `parallel_reduce` are both host functions, we are generating multiple warnings like this :
```
/var/jenkins/workspace/Kokkos/algorithms/unit_tests/../src/std_algorithms/Kokkos_ModifyingOperations.hpp(111): warning:
calling a __host__ function("Kokkos::parallel_for< (...) > ") from a __host__ __device__ function ("Kokkos::Experimental::iter_swap<(...)> ") is not allowed
```
[CUDA NVCC Debug build](https://cloud.cees.ornl.gov/jenkins-ci/blue/rest/organizations/jenkins/pipelines/Kokkos/runs/5961/nodes/50/steps/227/log/?start=0)

**Comment by fnrizzi** [comment]
@cz4rs not really, pfor and preduce also exist as device functions. 
I think the problem is that we are using the pfor and preduce overloads that take the range policy. So for those yes, they are only host.

**Comment by fnrizzi** [comment]
i am removing the macro where we don't need it

**Comment by fnrizzi** [comment]
fixed warnings: https://cloud.cees.ornl.gov/jenkins-ci/blue/rest/organizations/jenkins/pipelines/Kokkos/runs/5963/nodes/50/steps/227/log/?start=0
