### ISSUE TITLE
algorithms: need to think about the order of the arguments 

### ISSUE THREAD

**Issue by fnrizzi** [NexGenAnalytics/kokkos#20]
Considering we might end up with various overloads, we need to think about the best order to expose, keeping mind that we should stay compliant with the std. I think this order will be important when passing labels, and policies.

**Comment by fnrizzi** [comment]
looking at this, I think it makes sense to keep:
```cpp
function(iterators [, other things e.g. custom predicates])
function(label, iterators, [, other things e.g. custom predicates])
function(view, [, other things e.g. custom predicates])
function(label, view, [, other things e.g. custom predicates])

```

**Comment by cz4rs** [comment]
:+1: for this, label first (when used) to keep it consistent with Kokkos, otherwise as close to standard library as possible.
