### ISSUE TITLE
algorithms: extract common functors / bits into a separate header

### ISSUE THREAD

**Issue by cz4rs** [NexGenAnalytics/kokkos#32]
Algorithms requiring default comparators (and possibly others) could use common functors.

For reference, see [predefined_ops.h](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/predefined_ops.h).

**Comment by fnrizzi** [comment]
see this: https://github.com/NexGenAnalytics/kokkos/blob/for_each_4075/algorithms/src/std_algorithms/Kokkos_HelperPredicates.hpp
