### ISSUE TITLE
algo: checklist for each algorithm [do not close]

### ISSUE THREAD

**Issue by fnrizzi** [NexGenAnalytics/kokkos#38]
to finalize an algorithm, ensure the following list of things is done:
- `exespace` instance is taken by const ref (consistent with how exespace is used in other kokkos things)
   
- for view-accepting APIs use this: 
   ```cpp
   template <... , class DataType, class... Properties>
   void my_function_name( ...)

   // or for multiple views

   template <..., 
         class DataType1, class... Properties1, 
         class DataType2, class... Properties2>
   void my_function_name( ...)
   ```

- execution space is always first argument, except when we have a label which is first. So this: 
  ```cpp
  void function(ex_space, iterator, ...);
  void function(label, ex_space, iterator, ...);
  ```

- name default labels consistently:
   - for iterator-accepting APIs: use: `algo_name_iterator_api_default`
   - for view-accepting APIs: use: `algo_name_view_api_default`

- ensure `KOKKOS_INLINE_FUNCTION` is used appropriately

- ensure these things are done: 
  - views should be admissible to std algorithms (use `static_assert_is_admissible_to_kokkos_std_algorithms`)
  -  iterators and views should be accessible from the execution space provided (`static_assert_random_access_and_accessible`)
  - fencing is done appropriately and label conforms to: `fence("Kokkos::algoname: fence after operation")`

- ensure for each algo that we check its requirements as specified by the std

- any functor needed for implementations should be named as: 
  ```cpp
  struct AlgonameSomethingelseFunctor;
  ```
  for example: `StdFindIfOrNotFunctor` `StdForEachFunctor`

- for the view-accepting API: when calling the impl, make sure you use `cbegin/cend` for when we need a const-value dereferencing and `begin/end` only when we don't need const. 
 
- ensure no overloads are missing

- use `move` wherever possible

- Using `constexpr` to qualify each algorithm: we are holding off for this until the end. Strictly speaking, `constexpr` is used in the std to qualify functions only from c++20. 

anything else?

**Comment by cz4rs** [comment]
@fnrizzi 
We should pick one convention for the functors:

`StdModSeqOpCopyFunctor`, `StdModSeqOpFillFunctor`
vs
`StdFindIfOrNotFunctor`, `StdForEachFunctor`

Personally, I think that the latter (more concise) option is enough.

**Comment by fnrizzi** [comment]
I agree with you

**Comment by fnrizzi** [comment]
I think we forgot one: we need to make all functions `constexpr`

**Comment by cz4rs** [comment]
Note: we sometimes use move the functors (`KE::move(functor)`) into the implementation:
```cpp
  return Impl::for_each_n_impl("kokkos_for_each_n_view_api_default", ex,
                               KE::begin(v), n, KE::move(functor));
```
and sometimes we just pass them (by value):
```cpp
  return Impl::count_if_impl("kokkos_count_if_iterator_api_default", ex, first,
                             last, predicate);
```

@fnrizzi do you think that we should stick with one option?

**Comment by fnrizzi** [comment]
yes definitely! we should move every time we can . what do you think?

**Comment by cz4rs** [comment]
Agreed, I will update the calls.

**Comment by fnrizzi** [comment]
i just updated the list above

**Comment by cz4rs** [comment]
Closing after Algorithms PR was merged.
