### ISSUE TITLE
algorithms: problem with `TestStdAlgorithmsCommon.hpp`

### ISSUE THREAD

**Issue by fnrizzi** [NexGenAnalytics/kokkos#41]
@cz4rs , I noticed you moved everything into single Common.hpp. 
The reason why I did not do that before is that now inside COmmon.hpp we have:
```
// helpers for testing small views (extent = 10)
// prefer `default_scenarios` map for creating new tests
using value_type = double;
using exespace   = Kokkos::DefaultExecutionSpace;
```
which creates a bunch of shadowing issues. 
Either we get rid of all the old way to do tests, or we need to move these back to a separate header.

**Comment by cz4rs** [comment]
Ok, I think that removing the conflicting alias should be enough. I will take a look at it on Monday.

**Comment by fnrizzi** [comment]
yes but that means all tests using that alias will ahve issues right? anyway, let's talk on monday!

**Comment by cz4rs** [comment]
No more warnings appear. Closing.
