### ISSUE TITLE
algo: the test for mismatch is not using any values? 

### ISSUE THREAD

**Issue by fnrizzi** [NexGenAnalytics/kokkos#42]
@cz4rs the test for mismatch is using views that have no data , just the default initialization. 
I think this test needs to be changed. 
are there other tests where you did the same, i.e. not filling with values?

**Comment by cz4rs** [comment]
@fnrizzi 
The actual tests for `mismatch` (using the old testing infrastructure) are here:
https://github.com/NexGenAnalytics/kokkos/blob/8d45d5d4c688b9794558d0ed205d300415b50a46/algorithms/unit_tests/TestStdAlgorithmsNonModSeqOps.cpp#L56-L240

`TestStdAlgorithmsMismatch.cpp` was created to switch to new testing approach, but we have ceased to work on that (priorities etc.). Considering how much time we have left, the quickest way to handle this is to remove `TestStdAlgorithmsMismatch.cpp` and rely on the old tests. Are you ok with this? (btw this is the last one from non-mod-seq-ops, so there shouldn't be any other "phony" tests).

**Comment by fnrizzi** [comment]
@cz4rs i started rewriting `TestStdAlgorithmsMismatch.cpp` :) crap! 
well, I guess we will have more than we need, but even better

**Comment by fnrizzi** [comment]
in fact, all of this came up because the test fails on OpenMPTarget:
https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Kokkos/detail/Kokkos/6638/pipeline/45/

so that is why i started digging deeper. But the tests from NonModSeqOps work. caveat is that those are done on small views.

**Comment by fnrizzi** [comment]
fixed
